services:
  lavian_et_al_2025:
    container_name: lavian_et_al_2025
    build:
      context: .
      args:
        ENV_FILE: environment.docker.yml
    ports:
      - "8888:8888"
    environment:
      JUPYTER_TOKEN: "264a37c4aba8d47d712277f228384f88"
      XDG_CACHE_HOME: "/tmp/.cache"
      HOME: "/work"
      JUPYTER_RUNTIME_DIR: "/tmp/jupyter-runtime"
    user: "1000:1000"
    volumes:
      - .:/work
      - ./data:/work/data
