name: vis_nav
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=2.2.0
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - async_generator=1.10
  - attrs=20.3.0
  - av=8.0.3
  - babel=2.9.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - blas=1.0
  - bleach=3.3.0
  - blosc=1.21.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2021.10.8
  - cffi=1.14.5
  - chardet=4.0.0
  - charls=2.2.0
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cryptography=3.4.6
  - cycler=0.10.0
  - cytoolz=0.11.0
  - decorator=4.4.2
  - defusedxml=0.7.1
  - entrypoints=0.3
  - ffmpeg=4.3.1
  - freeglut=3.2.1
  - freetype=2.10.4
  - giflib=5.2.1
  - git=2.30.2
  - hdf5=1.10.6
  - icu=68.1
  - idna=2.10
  - imagecodecs=2021.1.28
  - imageio=2.9.0
  - importlib-metadata=3.7.3
  - intel-openmp=2020.3
  - ipycanvas=0.8.2
  - ipyevents=0.8.2
  - ipykernel=5.5.0
  - ipympl=0.7.0
  - ipython=7.21.0
  - ipython_genutils=0.2.0
  - jasper=2.0.14
  - jedi=0.18.0
  - jinja2=2.11.3
  - joblib=1.0.1
  - jpeg=9d
  - json5=0.9.5
  - jsonschema=3.2.0
  - jupyter-packaging=0.7.12
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyter_server=1.5.1
  - jupyterlab=3.0.12
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.3.0
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.12
  - lerc=2.2.1
  - libaec=1.0.4
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.75.0
  - libdeflate=1.7
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libopencv=4.5.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - libzopfli=1.0.3
  - llvmlite=0.36.0
  - lz4-c=1.9.3
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - mistune=0.8.4
  - mkl=2020.4
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - mock=4.0.3
  - nbclassic=0.2.6
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nest-asyncio=1.4.3
  - networkx=2.5
  - nodejs=17.9.0
  - notebook=6.3.0
  - numexpr=2.7.3
  - numpy-base=1.19.2
  - olefile=0.46
  - opencv=4.5.1
  - openjpeg=2.4.0
  - openssl=1.1.1n
  - orjson=3.5.1
  - packaging=20.9
  - pandas=1.2.3
  - pandoc=2.13
  - pandocfilters=1.4.2
  - parso=0.8.1
  - patsy=0.5.2
  - pickleshare=0.7.5
  - pillow=8.1.2
  - pooch=1.3.0
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.18
  - py-opencv=4.5.1
  - pycparser=2.20
  - pygments=2.8.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyqtchart=5.12
  - pyqtwebengine=5.12.1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.10
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2021.1
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - pyzmq=22.0.3
  - qt=5.12.9
  - requests=2.25.1
  - scikit-image=0.18.1
  - scikit-learn=0.24.1
  - send2trash=1.5.0
  - six=1.15.0
  - snappy=1.1.8
  - sniffio=1.2.0
  - sqlite=3.35.2
  - statsmodels=0.12.2
  - terminado=0.9.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - urllib3=1.26.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.4
  - zfp=0.5.5
  - zipp=3.4.1
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - aicsimageio==4.7.0
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - alabaster==0.7.12
    - anytree==2.8.0
    - arrayqueues==1.3.1
    - asciitree==0.3.3
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - bcrypt==3.2.0
    - bg-atlasapi==1.0.0
    - bg-space==0.5.0
    - black==20.8b1
    - bouter==0.2.0
    - brainrender==2.0.5.3
    - bs4==0.0.1
    - cachey==0.2.1
    - cellpose==2.2.1
    - charset-normalizer==2.1.1
    - circle-fit==0.1.3
    - click==7.1.2
    - cmocean==2.0
    - colorspacious==1.1.2
    - commonmark==0.9.1
    - czifile==2019.7.2
    - dask==2022.2.0
    - deepdish==0.3.7
    - deprecated==1.2.13
    - dnspython==2.3.0
    - docstring-parser==0.7.3
    - docutils==0.16
    - elementpath==4.1.1
    - email-validator==2.0.0.post2
    - fasteners==0.18
    - fastjsonschema==2.16.1
    - fastremap==1.13.5
    - flammkuchen==0.9.2
    - freetype-py==2.2.0
    - frozenlist==1.3.1
    - fsspec==2023.1.0
    - future==0.18.2
    - gitdb==4.0.7
    - gitpython==3.1.17
    - google==3.0.0
    - h5py==3.1.0
    - heapdict==1.0.1
    - helpdev==0.7.1
    - hsluv==5.0.3
    - imageio-ffmpeg==0.4.4
    - imagesize==1.2.0
    - ipydatawidgets==4.3.2
    - ipynbname==2021.3.2
    - ipyvtklink==0.2.3
    - ipywidgets==7.7.2
    - jupyter-server==1.6.4
    - k3d==2.7.4
    - lightparam==0.4.6
    - locket==1.0.0
    - loguru==0.6.0
    - magicgui==0.6.1
    - markupsafe==2.1.1
    - matplotlib-scalebar==0.8.0
    - meshio==5.0.4
    - morphapi==0.1.7
    - morphio==3.3.3
    - mpmath==1.2.1
    - msgpack==1.0.4
    - multidict==6.0.2
    - mycolorpy==1.5.1
    - mypy-extensions==0.4.3
    - myterial==1.2.1
    - napari==0.4.14
    - napari-aicsimageio==0.2.0
    - napari-animation==0.0.2
    - napari-console==0.0.7
    - napari-plugin-engine==0.1.9
    - napari-split-dataset==0.2.0
    - napari-svg==0.1.4
    - natsort==7.1.1
    - nbformat==5.5.0
    - neurom==3.2.2
    - npe2==0.2.1
    - npx==0.0.24
    - numba==0.53.1
    - numcodecs==0.10.2
    - numpy==1.21.6
    - numpydoc==1.1.0
    - ome-types==0.3.4
    - opencv-python-headless==4.7.0.72
    - paramiko==2.7.2
    - partd==1.4.0
    - pathspec==0.8.1
    - pims==0.5
    - pint==0.17
    - pip==24.0
    - plotly==4.14.3
    - psutil==5.8.0
    - psygnal==0.8.1
    - py==1.11.0
    - pydantic==1.8.1
    - pyinspect==0.1.0
    - pynacl==1.4.0
    - pynrrd==0.4.2
    - pyopengl==3.1.5
    - pyqt5==5.15.9
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.12.1
    - pyqtgraph==0.12.3
    - pyquaternion==0.9.9
    - pytomlpp==1.0.13
    - qdarkstyle==2.8.1
    - qimage2ndarray==1.8.3
    - qtconsole==5.0.3
    - qtpy==1.11.2
    - rastermap==0.1.3
    - regex==2021.3.17
    - retry==0.9.2
    - retrying==1.3.3
    - rich==10.15.0
    - sbxreader==0.1.5
    - scanimage-tiff-reader==1.4.1
    - scipy==1.7.3
    - seaborn==0.11.2
    - setuptools==65.3.0
    - slicerator==1.0.0
    - smmap==4.0.0
    - snowballstemmer==2.1.0
    - soupsieve==2.3.2.post1
    - sphinx==3.5.3
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - split-dataset==0.4.2
    - stytra==0.8.34
    - suite2p==0.10.1
    - superqt==0.4.1
    - svgpath2mpl==1.0.0
    - sympy==1.8
    - tables==3.7.0
    - tifffile==2021.11.2
    - toml==0.10.2
    - torch==1.11.0
    - tqdm==4.61.1
    - traitlets==5.4.0
    - traittypes==0.2.1
    - treelib==1.6.1
    - trimesh==3.9.10
    - typed-ast==1.4.3
    - typer==0.9.0
    - typing-extensions==3.10.0.2
    - vedo==2021.0.5
    - vispy==0.10.0
    - vtk==9.2.2
    - widgetsnbextension==3.6.1
    - wrapt==1.12.1
    - wslink==1.9.0
    - xarray==0.18.2
    - xmlschema==2.2.3
    - yarl==1.8.1
    - zarr==2.12.0
