name: vis_nav
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=2.2.0=py37h03978a9_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argon2-cffi=20.1.0=py37hcc03f2d_2
  - async_generator=1.10=py_0
  - attrs=20.3.0=pyhd3deb0d_0
  - av=8.0.3=py37h5adff53_0
  - babel=2.9.0=pyhd3deb0d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.3.0=pyh44b312d_0
  - blosc=1.21.0=h0e60522_0
  - brotli=1.0.9=h0e60522_4
  - brotlipy=0.7.0=py37hcc03f2d_1001
  - bzip2=1.0.8=h8ffe710_4
  - ca-certificates=2021.10.8=h5b45459_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2021.10.8=py37h03978a9_2
  - cffi=1.14.5=py37hd8e9650_0
  - chardet=4.0.0=py37h03978a9_1
  - charls=2.2.0=h39d44d4_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cryptography=3.4.6=py37h20c650d_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py37hcc03f2d_3
  - decorator=4.4.2=py_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - ffmpeg=4.3.1=ha925a31_0
  - freeglut=3.2.1=h0e60522_2
  - freetype=2.10.4=h546665d_1
  - giflib=5.2.1=h8d14728_2
  - git=2.30.2=h57928b3_0
  - hdf5=1.10.6=nompi_h5268f04_1114
  - icu=68.1=h0e60522_0
  - idna=2.10=pyh9f0ad1d_0
  - imagecodecs=2021.1.28=py37hb664a41_0
  - imageio=2.9.0=py_0
  - importlib-metadata=3.7.3=py37h03978a9_0
  - intel-openmp=2020.3=h57928b3_311
  - ipycanvas=0.8.2=pyhd8ed1ab_0
  - ipyevents=0.8.2=pyhd8ed1ab_0
  - ipykernel=5.5.0=py37heaed05f_1
  - ipympl=0.7.0=pyhd8ed1ab_0
  - ipython=7.21.0=py37heaed05f_0
  - ipython_genutils=0.2.0=py_1
  - jasper=2.0.14=h77af90b_2
  - jedi=0.18.0=py37h03978a9_2
  - jinja2=2.11.3=pyh44b312d_0
  - joblib=1.0.1=pyhd8ed1ab_0
  - jpeg=9d=h8ffe710_0
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter-packaging=0.7.12=pyhd8ed1ab_0
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py37h03978a9_0
  - jupyter_server=1.5.1=py37h03978a9_0
  - jupyterlab=3.0.12=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.3.0=pyhd8ed1ab_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - jxrlib=1.1=h8ffe710_2
  - kiwisolver=1.3.1=py37h8c56517_1
  - krb5=1.17.2=hbae68bd_0
  - lcms2=2.12=h2a16943_0
  - lerc=2.2.1=h0e60522_0
  - libaec=1.0.4=h39d44d4_1
  - libblas=3.9.0=8_mkl
  - libcblas=3.9.0=8_mkl
  - libclang=11.1.0=default_h5c34c98_0
  - libcurl=7.75.0=hf1763fc_0
  - libdeflate=1.7=h8ffe710_5
  - liblapack=3.9.0=8_mkl
  - liblapacke=3.9.0=8_mkl
  - libopencv=4.5.1=py37ha0199f4_0
  - libpng=1.6.37=h1d00b33_2
  - libsodium=1.0.18=h8d14728_1
  - libssh2=1.9.0=h680486a_6
  - libtiff=4.2.0=hc10be44_0
  - libwebp-base=1.2.0=h8ffe710_2
  - libzopfli=1.0.3=h0e60522_0
  - llvmlite=0.36.0=py37habb0c8c_0
  - lz4-c=1.9.3=h8ffe710_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.3.4=py37h03978a9_0
  - matplotlib-base=3.3.4=py37h3379fd5_0
  - mistune=0.8.4=py37hcc03f2d_1003
  - mkl=2020.4=hb70f87d_311
  - mkl-service=2.3.0=py37h196d8e1_0
  - mkl_fft=1.3.0=py37h46781fe_0
  - mkl_random=1.1.1=py37h47e9c7a_0
  - mock=4.0.3=py37h03978a9_1
  - msys2-conda-epoch=20160418=1
  - nbclassic=0.2.6=pyhd8ed1ab_0
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.0.7=py37h03978a9_3
  - nest-asyncio=1.4.3=pyhd8ed1ab_0
  - networkx=2.5=py_0
  - nodejs=17.9.0=h57928b3_0
  - notebook=6.3.0=py37h03978a9_0
  - numexpr=2.7.3=py37h08fd248_0
  - numpy-base=1.19.2=py37ha3acd2a_0
  - olefile=0.46=pyh9f0ad1d_1
  - opencv=4.5.1=py37h03978a9_0
  - openjpeg=2.4.0=h48faf41_0
  - openssl=1.1.1n=h8ffe710_0
  - orjson=3.5.1=py37h03978a9_0
  - packaging=20.9=pyh44b312d_0
  - pandas=1.2.3=py37h08fd248_0
  - pandoc=2.13=h8ffe710_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.1=pyhd8ed1ab_0
  - patsy=0.5.2=py37haa95532_1
  - pickleshare=0.7.5=py_1003
  - pillow=8.1.2=py37h96663a1_0
  - pooch=1.3.0=pyhd8ed1ab_0
  - prometheus_client=0.9.0=pyhd3deb0d_0
  - prompt-toolkit=3.0.18=pyha770c72_0
  - py-opencv=4.5.1=py37heaed05f_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.8.1=pyhd8ed1ab_0
  - pyopenssl=20.0.1=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py37h03978a9_7
  - pyqtchart=5.12=py37hf2a7229_7
  - pyqtwebengine=5.12.1=py37hf2a7229_7
  - pyreadline=2.1=py37h03978a9_1003
  - pyrsistent=0.17.3=py37hcc03f2d_2
  - pysocks=1.7.1=py37h03978a9_3
  - python=3.7.10=h7840368_100_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2021.1=pyhd8ed1ab_0
  - pywavelets=1.1.1=py37hda49f71_3
  - pywin32=300=py37hcc03f2d_0
  - pywinpty=0.5.7=py37hc8dfbb8_1
  - pyyaml=5.4.1=py37hcc03f2d_0
  - pyzmq=22.0.3=py37hcce574b_1
  - qt=5.12.9=h5909a2a_4
  - requests=2.25.1=pyhd3deb0d_0
  - scikit-image=0.18.1=py37h08fd248_0
  - scikit-learn=0.24.1=py37heb15398_0
  - send2trash=1.5.0=py_0
  - six=1.15.0=pyh9f0ad1d_0
  - snappy=1.1.8=ha925a31_3
  - sniffio=1.2.0=py37h03978a9_1
  - sqlite=3.35.2=h8ffe710_0
  - statsmodels=0.12.2=py37h2bbff1b_0
  - terminado=0.9.3=py37h03978a9_0
  - testpath=0.4.4=py_0
  - threadpoolctl=2.1.0=pyh5ca1d4c_0
  - tk=8.6.10=h8ffe710_1
  - toolz=0.11.1=py_0
  - tornado=6.1=py37hcc03f2d_1
  - urllib3=1.26.4=pyhd8ed1ab_0
  - vc=14.2=hb210afc_4
  - vs2015_runtime=14.28.29325=h5e1d092_4
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3deb0d_0
  - win_inet_pton=1.1.0=py37h03978a9_2
  - wincertstore=0.2=py37h03978a9_1006
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.4=h0e60522_0
  - zfp=0.5.5=h0e60522_4
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.4.9=h6255e5f_0
  - pip:
    - aicsimageio==4.7.0
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - alabaster==0.7.12
    - anytree==2.8.0
    - arrayqueues==1.3.1
    - asciitree==0.3.3
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - bcrypt==3.2.0
    - bg-atlasapi==1.0.0
    - bg-space==0.5.0
    - black==20.8b1
    - bouter==0.2.0
    - brainrender==2.0.5.3
    - bs4==0.0.1
    - cachey==0.2.1
    - cellpose==2.2.1
    - charset-normalizer==2.1.1
    - circle-fit==0.1.3
    - click==7.1.2
    - cmocean==2.0
    - colorspacious==1.1.2
    - commonmark==0.9.1
    - czifile==2019.7.2
    - dask==2022.2.0
    - deepdish==0.3.7
    - deprecated==1.2.13
    - dnspython==2.3.0
    - docstring-parser==0.7.3
    - docutils==0.16
    - elementpath==4.1.1
    - email-validator==2.0.0.post2
    - fasteners==0.18
    - fastjsonschema==2.16.1
    - fastremap==1.13.5
    - flammkuchen==0.9.2
    - freetype-py==2.2.0
    - frozenlist==1.3.1
    - fsspec==2023.1.0
    - future==0.18.2
    - gitdb==4.0.7
    - gitpython==3.1.17
    - google==3.0.0
    - h5py==3.1.0
    - heapdict==1.0.1
    - helpdev==0.7.1
    - hsluv==5.0.3
    - imageio-ffmpeg==0.4.4
    - imagesize==1.2.0
    - ipydatawidgets==4.3.2
    - ipynbname==2021.3.2
    - ipyvtklink==0.2.3
    - ipywidgets==7.7.2
    - jupyter-server==1.6.4
    - k3d==2.7.4
    - lightparam==0.4.6
    - locket==1.0.0
    - loguru==0.6.0
    - magicgui==0.6.1
    - markupsafe==2.1.1
    - matplotlib-scalebar==0.8.0
    - meshio==5.0.4
    - morphapi==0.1.7
    - morphio==3.3.3
    - mpmath==1.2.1
    - msgpack==1.0.4
    - multidict==6.0.2
    - mycolorpy==1.5.1
    - mypy-extensions==0.4.3
    - myterial==1.2.1
    - napari==0.4.14
    - napari-aicsimageio==0.2.0
    - napari-animation==0.0.2
    - napari-console==0.0.7
    - napari-plugin-engine==0.1.9
    - napari-split-dataset==0.2.0
    - napari-svg==0.1.4
    - natsort==7.1.1
    - nbformat==5.5.0
    - neurom==3.2.2
    - npe2==0.2.1
    - npx==0.0.24
    - numba==0.53.1
    - numcodecs==0.10.2
    - numpy==1.21.6
    - numpydoc==1.1.0
    - ome-types==0.3.4
    - opencv-python-headless==4.7.0.72
    - paramiko==2.7.2
    - partd==1.4.0
    - pathspec==0.8.1
    - pims==0.5
    - pint==0.17
    - pip==24.0
    - plotly==4.14.3
    - psutil==5.8.0
    - psygnal==0.8.1
    - py==1.11.0
    - pydantic==1.8.1
    - pyinspect==0.1.0
    - pynacl==1.4.0
    - pynrrd==0.4.2
    - pyopengl==3.1.5
    - pyqt5==5.15.9
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.12.1
    - pyqtgraph==0.12.3
    - pyquaternion==0.9.9
    - pytomlpp==1.0.13
    - qdarkstyle==2.8.1
    - qimage2ndarray==1.8.3
    - qtconsole==5.0.3
    - qtpy==1.11.2
    - rastermap==0.1.3
    - regex==2021.3.17
    - retry==0.9.2
    - retrying==1.3.3
    - rich==10.15.0
    - sbxreader==0.1.5
    - scanimage-tiff-reader==1.4.1
    - scipy==1.7.3
    - seaborn==0.11.2
    - setuptools==65.3.0
    - slicerator==1.0.0
    - smmap==4.0.0
    - snowballstemmer==2.1.0
    - soupsieve==2.3.2.post1
    - sphinx==3.5.3
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==1.0.3
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.4
    - split-dataset==0.4.2
    - stytra==0.8.34
    - suite2p==0.10.1
    - superqt==0.4.1
    - svgpath2mpl==1.0.0
    - sympy==1.8
    - tables==3.7.0
    - tifffile==2021.11.2
    - toml==0.10.2
    - torch==1.11.0
    - tqdm==4.61.1
    - traitlets==5.4.0
    - traittypes==0.2.1
    - treelib==1.6.1
    - trimesh==3.9.10
    - typed-ast==1.4.3
    - typer==0.9.0
    - typing-extensions==3.10.0.2
    - vedo==2021.0.5
    - vispy==0.10.0
    - vtk==9.2.2
    - widgetsnbextension==3.6.1
    - win32-setctime==1.1.0
    - wrapt==1.12.1
    - wslink==1.9.0
    - xarray==0.18.2
    - xmlschema==2.2.3
    - yarl==1.8.1
    - zarr==2.12.0
prefix: C:\Users\lavian\anaconda3\envs\vis_nav
